
-- PATCH DE LIAISON TRANSACTIONNELLE
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS sale_id UUID REFERENCES sales(id) ON DELETE SET NULL;

-- INDEX DE RECHERCHE RAPIDE POUR MODIFICATION
CREATE INDEX IF NOT EXISTS idx_invoices_sale_id ON invoices(sale_id);
