
-- PATCH DE DÉBRIDAGE DES VENTES DIRECTES
ALTER TABLE invoices ALTER COLUMN customer_id DROP NOT NULL;
ALTER TABLE sales ALTER COLUMN customer_id DROP NOT NULL;

-- MISE À JOUR INDEX
CREATE INDEX IF NOT EXISTS idx_sales_status ON sales(status);
